{{- if .Values.psp.create }}
{{- $pspApiIsDeprecated := eq (include "psp.isDeprecated" .) "true" -}}
{{- if not $pspApiIsDeprecated }}
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: {{ .Release.Name }}-psp
spec:
  privileged: true
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  runAsUser:
    rule: RunAsAny
  fsGroup:
    rule: RunAsAny
  volumes:
  - '*'
{{- end }}
{{- end }}