apiVersion: v1
kind: Service
metadata:
  name: {{ include "pacman.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pacman.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "pacman.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: {{ .Release.Name }}-mongo-backend
  name: {{ .Release.Name }}-mongo-backend
spec:
  type: ClusterIP
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP
      name: mongodb
  selector:
    name: {{ .Release.Name }}-mongo-backend