apiVersion: v2
appVersion: 0.1.0
version: 0.1.0
name: pacman
description: Pac-Man for Kubernetes
home: https://github.com/shuguet/pacman-kube
icon: https://www.huguet.me
sources:
  - https://github.com/shuguet/pacman-kube
maintainers:
  - name: Dean Lewis
    url: https://veducate.co.uk
  - name: Davis Phillips
    url: https://github.com/dav1x/
  - name: Michael Cade
    url: https://vzilla.co.uk/
  - name: Sylvain Huguet
    url: https://www.huguet.me
